### ISSUE TITLE
[Suggestion] Add shortcut key

### ISSUE THREAD

**Issue by RoonMoonlight** [Jofre-Problem/JofreHUD#2]
Hi there, I want to suggest some feature to be added to JofreHUD.

While most huds supporting the shortcut key feature (e.g. Pressing E on class select will open the loadout menu), but this hud doesn't support it.

This is my favorite TF2 hud and I would like this feature to be added!

### Class Select Screen
E - Open loadout
R - Random class
1~9 - Select class key (Scout, Soldier, Pyro, Demoman, Heavy, Engineer, Medic, Sniper, Spy)

### Items Screen
Q/E - Switch inventory page (Left/Right)

**Comment by Jofre-Problem** [comment]
Done. I didnt expect people using this HUD as their main HUD, but glad you like it! :)
